[package]
name = "gullery_macros"
version = "0.1.0"
authors = ["Osspial <osspial@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = {version="1", features=["derive"]}
quote = "1"
proc-macro2 = "1"
