[package]
name = "gl_raii"
version = "0.1.0"
authors = ["Osspial <osspial@gmail.com>"]

[dependencies]
gl_raw = {path = "./gl_raw"}
num-traits = "0.1"
derive_more = "0.6"

[dev-dependencies]
glutin = "0.8"
quickcheck = "0.4"

[workspace]
members = ["./gl_raw"]
