[package]
name = "gl_raii"
version = "0.1.0"
authors = ["Osspial <osspial@gmail.com>"]

[dependencies]
gl_raw = {path = "./gl_raw"}
derive_more = "0.6"
num-traits = "0.1"
cgmath = "^0.14"
log = "0.3"

[dev-dependencies]
glutin = "0.8"
quickcheck = "0.4"
gl_raii_macros = {path = "./gl_raii_macros"}

[workspace]
members = ["./gl_raw", "./gl_raii_macros"]
